# Neural Operator Continuous Time Consistency Model Configuration
# Optimized for CIFAR-10 single-step generation

model:
  type: "NO-CTCM"

  # UNet backbone configuration
  backbone:
    type: "unet"
    use_simple: false  # Use full UNet
    in_channels: 3
    out_channels: 3
    channels: 128
    channel_mult: [1, 2, 2, 2]
    num_res_blocks: 2
    attention_resolutions: [16, 8]
    dropout: 0.0
    use_checkpoint: false
    num_heads: 4
    num_head_channels: 64
    use_scale_shift_norm: true
    resblock_updown: true

  # Neural operator configuration
  neural_operator:
    use_fno: true
    fno_modes: 16
    fno_width: 128
    fno_layers: 4
    spectral_normalization: true

  # Time conditioning (TrigFlow style)
  time_conditioning:
    type: "trigflow"
    embed_dim: 256
    positional_encoding: true
    fourier_scale: 1.0
    adaptive_norm: true
    pixel_norm: true

  # Consistency model specifics
  consistency:
    parameterization: "v-prediction"
    sigma_data: 0.5
    sigma_min: 0.002
    sigma_max: 80.0
    rho: 7.0

data:
  dataset: "cifar10"
  image_size: 32
  channels: 3
  flip_prob: 0.5
  normalize: true
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  num_workers: 4

training:
  # ADD THIS LINE - specify the training mode
  mode: "consistency_training"  # or "distillation"

  # Basic settings
  batch_size: 128
  total_iterations: 100000

  # Optimizer
  optimizer:
    type: "adamw"
    lr: 3e-4
    betas: [0.9, 0.99]
    weight_decay: 1e-2
    eps: 1e-8

  # Learning rate schedule
  lr_scheduler:
    type: "cosine"
    warmup_steps: 5000
    min_lr: 1e-6

  # Loss configuration
  loss:
    type: "pseudo_huber"
    c: 0.01
    reduction: "mean"

  # Progressive training schedule
  progressive:
    enabled: true
    initial_discretization: 18
    final_discretization: 1280
    doubling_iterations: 20000

  # EMA configuration
  ema:
    enabled: true
    decay: 0.9999
    update_every: 10

  # Gradient clipping
  gradient_clip: 1.0

  # Checkpointing
  checkpoint:
    save_every: 5000
    keep_last: 5

  # Logging
  log_every: 100
  sample_every: 1000

  # Multi-GPU
  distributed:
    enabled: false
    backend: "nccl"

sampling:
  num_steps: 1  # Single-step generation
  solver: "euler"
  guidance_scale: 0.0  # No guidance for unconditional

evaluation:
  batch_size: 256
  num_samples: 50000
  metrics: ["fid", "is", "precision", "recall"]

# Weights & Biases logging
wandb:
  enabled: false  # Set to true if you want to use wandb
  project: "neural-consistency-model"
  entity: null  # Set your entity
  tags: ["cifar10", "ctcm", "fno"]

# Paths
paths:
  data_dir: "./data"
  checkpoint_dir: "./checkpoints"
  sample_dir: "./samples"
  log_dir: "./logs"