# Simple test configuration for CIFAR-10
# Minimal complexity for debugging

model:
  type: "NO-CTCM"

  backbone:
    type: "unet"
    use_simple: true  # Use simplified UNet
    in_channels: 3
    out_channels: 3
    channels: 64
    channel_mult: [1, 2, 2]
    num_res_blocks: 1
    attention_resolutions: []
    dropout: 0.0
    use_checkpoint: false
    num_heads: 4
    num_head_channels: 32
    use_scale_shift_norm: true
    resblock_updown: false

  neural_operator:
    use_fno: false  # Disable FNO for simplicity
    fno_modes: 16
    fno_width: 128
    fno_layers: 4
    spectral_normalization: false

  time_conditioning:
    type: "trigflow"
    embed_dim: 256
    positional_encoding: true
    fourier_scale: 1.0
    adaptive_norm: true
    pixel_norm: false

  consistency:
    parameterization: "v-prediction"
    sigma_data: 0.5
    sigma_min: 0.002
    sigma_max: 80.0
    rho: 7.0

data:
  dataset: "cifar10"
  image_size: 32
  channels: 3
  flip_prob: 0.5
  normalize: true
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  num_workers: 4

training:
  mode: "consistency_training"
  batch_size: 32
  total_iterations: 1000  # Very short for testing

  optimizer:
    type: "adamw"
    lr: 1e-4
    betas: [0.9, 0.99]
    weight_decay: 1e-2
    eps: 1e-8

  lr_scheduler:
    type: "cosine"
    warmup_steps: 100
    min_lr: 1e-6

  loss:
    type: "pseudo_huber"
    c: 0.01
    reduction: "mean"

  progressive:
    enabled: false  # Disable for simplicity

  ema:
    enabled: true
    decay: 0.999
    update_every: 10

  gradient_clip: 1.0

  checkpoint:
    save_every: 500
    keep_last: 2

  log_every: 10
  sample_every: 100

  distributed:
    enabled: false

sampling:
  num_steps: 1
  solver: "euler"
  guidance_scale: 0.0

evaluation:
  batch_size: 64
  num_samples: 1000
  metrics: ["fid"]

wandb:
  enabled: false
  project: "neural-consistency-model"

paths:
  data_dir: "./data"
  checkpoint_dir: "./checkpoints/test"
  sample_dir: "./samples/test"
  log_dir: "./logs/test"