# Training hyper‑parameters
dataset: CIFAR10
batch_size: 256
num_epochs: 800
image_size: 32
num_classes: 10

# Noise schedule
sigma_min: 0.002
sigma_max: 80.0
rho: 7.0          # Karras schedule exponent

# Model
fno:
  in_channels: 3
  out_channels: 3
  width: 128
  modes: 16
  layers: 6
  use_lowpass: true      # weighted‑mode “spectral re‑balancing”
  skip_conv: true        # local detail branch

# Optimiser
lr: 3.0e-4
weight_decay: 1.0e-2
ema_decay: 0.9999

# Loss weights
tangent_lambda: 0.1

# Checkpoints / logging
save_interval: 50
eval_interval: 10
