model:
  img_size: 32
  in_channels: 3
  base_dim: 128
  dim_mults: [1, 2, 2, 2]
  num_res_blocks: 2
  time_embed_dim: 256
  dropout: 0.1
train:
  batch_size: 128
  total_steps: 400_000
  lr: 3e-4
  weight_decay: 1e-3
  ema_decay: 0.9999
  sigma_data: 0.5
  sigma_min: 0.002
  sigma_max: 80.0
  rho: 7.0
  tangent_clip: 1.0
  warmup_steps: 10_000
  save_every: 10_000
eval:
  n_samples: 50_000
  fid_devices: "cuda"